
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyWebServiceImplementationService", targetNamespace = "http://jaxwsservice.com/", wsdlLocation = "http://localhost:8080/webservice/greeting?wsdl")
public class MyWebServiceImplementationService
    extends Service
{

    private final static URL MYWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName MYWEBSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://jaxwsservice.com/", "MyWebServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/greeting?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        MYWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public MyWebServiceImplementationService() {
        super(__getWsdlLocation(), MYWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public MyWebServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public MyWebServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, MYWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public MyWebServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public MyWebServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyWebServiceInterface
     */
    @WebEndpoint(name = "MyWebServiceImplementationPort")
    public MyWebServiceInterface getMyWebServiceImplementationPort() {
        return super.getPort(new QName("http://jaxwsservice.com/", "MyWebServiceImplementationPort"), MyWebServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebServiceInterface
     */
    @WebEndpoint(name = "MyWebServiceImplementationPort")
    public MyWebServiceInterface getMyWebServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxwsservice.com/", "MyWebServiceImplementationPort"), MyWebServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw MYWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return MYWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
